//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSOProductionService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://ws_sso.rd.go.th/ws_rdsso/Service", ConfigurationName="SSOProductionService.ServiceSoap")]
    public interface ServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws_sso.rd.go.th/ws_rdsso/Service/Get_SSO_User", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SSOProductionService.UserCls> Get_SSO_UserAsync(string UserID, string AppId, string Pwd_Authen);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws_sso.rd.go.th/ws_rdsso/Service/Get_SSO_User2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SSOProductionService.User2Cls> Get_SSO_User2Async(string UserID, string AppId, string Pwd_Authen);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws_sso.rd.go.th/ws_rdsso/Service/Get_SSO_UserByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SSOProductionService.UserIdCls> Get_SSO_UserByIDAsync(string UserID, string AppId, string Pwd_Authen);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws_sso.rd.go.th/ws_rdsso/Service/Get_SSO_UserPKIMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SSOProductionService.UserPKIMSCls> Get_SSO_UserPKIMSAsync(string UserID, string UserPKIMS_ID, string UserPKIMS_PWD);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws_sso.rd.go.th/ws_rdsso/Service/Get_SSO_Transaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SSOProductionService.TransCls> Get_SSO_TransactionAsync(string UserID, string AppId, string Pwd_Authen);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws_sso.rd.go.th/ws_rdsso/Service/Get_SSO_StatusUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SSOProductionService.UserStatusCls> Get_SSO_StatusUserAsync(string UserID, string AppId, string Pwd_Authen);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws_sso.rd.go.th/ws_rdsso/Service/Get_SSO_Client", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SSOProductionService.ClientCls> Get_SSO_ClientAsync(string ClientIP, string AppId, string Pwd_Authen);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws_sso.rd.go.th/ws_rdsso/Service/Get_Location_Name", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SSOProductionService.LocCls> Get_Location_NameAsync(string AppId, string Pwd_Authen, string Loc_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws_sso.rd.go.th/ws_rdsso/Service/Get_Job", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string[]> Get_JobAsync(string AppId, string Pwd_Authen, string Loc_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws_sso.rd.go.th/ws_rdsso/Service/Get_Job_Name", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SSOProductionService.JobCls> Get_Job_NameAsync(string AppId, string Pwd_Authen, string Job_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws_sso.rd.go.th/ws_rdsso/Service/TestAAB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> TestAABAsync(int A);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws_sso.rd.go.th/ws_rdsso/Service/Get_User_UnderLoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string[]> Get_User_UnderLocAsync(string AppId, string Pwd_Authen, string Loc_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws_sso.rd.go.th/ws_rdsso/Service/Get_User_UnderJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string[]> Get_User_UnderJobAsync(string AppId, string Pwd_Authen, string Loc_ID, string Job_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws_sso.rd.go.th/ws_rdsso/Service/SSO_APP_Transaction_Log", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SSOProductionService.UserLogCls> SSO_APP_Transaction_LogAsync(string UserID, string AppId, string TokenID, string AppTransID, string Pwd_Authen);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws_sso.rd.go.th/ws_rdsso/Service/SSO_App_LogOut", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SSOProductionService.UserLogCls> SSO_App_LogOutAsync(string UserID, string AppId, string TokenID, string Pwd_Authen);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws_sso.rd.go.th/ws_rdsso/Service")]
    public partial class UserCls
    {
        
        private string userIDField;
        
        private string userPINField;
        
        private string userRDCodeField;
        
        private string userPrefixField;
        
        private string userNameTHField;
        
        private string userSurNameTHField;
        
        private string userNameENField;
        
        private string userSurNameENField;
        
        private string userEMailField;
        
        private string userTypeField;
        
        private string userRankField;
        
        private string userPositionNoField;
        
        private string userOfficeCodeField;
        
        private string userJobIDField;
        
        private string userWorkCodeField;
        
        private string userWorkJobIDField;
        
        private string userLevelCField;
        
        private string userLevelNewField;
        
        private string userLoginDateTimeField;
        
        private string clientIPField;
        
        private string clientMACField;
        
        private string tokenIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserPIN
        {
            get
            {
                return this.userPINField;
            }
            set
            {
                this.userPINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UserRDCode
        {
            get
            {
                return this.userRDCodeField;
            }
            set
            {
                this.userRDCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UserPrefix
        {
            get
            {
                return this.userPrefixField;
            }
            set
            {
                this.userPrefixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string UserNameTH
        {
            get
            {
                return this.userNameTHField;
            }
            set
            {
                this.userNameTHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string UserSurNameTH
        {
            get
            {
                return this.userSurNameTHField;
            }
            set
            {
                this.userSurNameTHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string UserNameEN
        {
            get
            {
                return this.userNameENField;
            }
            set
            {
                this.userNameENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string UserSurNameEN
        {
            get
            {
                return this.userSurNameENField;
            }
            set
            {
                this.userSurNameENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string UserEMail
        {
            get
            {
                return this.userEMailField;
            }
            set
            {
                this.userEMailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string UserType
        {
            get
            {
                return this.userTypeField;
            }
            set
            {
                this.userTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string UserRank
        {
            get
            {
                return this.userRankField;
            }
            set
            {
                this.userRankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string UserPositionNo
        {
            get
            {
                return this.userPositionNoField;
            }
            set
            {
                this.userPositionNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string UserOfficeCode
        {
            get
            {
                return this.userOfficeCodeField;
            }
            set
            {
                this.userOfficeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string UserJobID
        {
            get
            {
                return this.userJobIDField;
            }
            set
            {
                this.userJobIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string UserWorkCode
        {
            get
            {
                return this.userWorkCodeField;
            }
            set
            {
                this.userWorkCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string UserWorkJobID
        {
            get
            {
                return this.userWorkJobIDField;
            }
            set
            {
                this.userWorkJobIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string UserLevelC
        {
            get
            {
                return this.userLevelCField;
            }
            set
            {
                this.userLevelCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string UserLevelNew
        {
            get
            {
                return this.userLevelNewField;
            }
            set
            {
                this.userLevelNewField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string UserLoginDateTime
        {
            get
            {
                return this.userLoginDateTimeField;
            }
            set
            {
                this.userLoginDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string ClientIP
        {
            get
            {
                return this.clientIPField;
            }
            set
            {
                this.clientIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string ClientMAC
        {
            get
            {
                return this.clientMACField;
            }
            set
            {
                this.clientMACField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string TokenID
        {
            get
            {
                return this.tokenIDField;
            }
            set
            {
                this.tokenIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws_sso.rd.go.th/ws_rdsso/Service")]
    public partial class UserLogCls
    {
        
        private string userIDField;
        
        private string returnCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ReturnCode
        {
            get
            {
                return this.returnCodeField;
            }
            set
            {
                this.returnCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws_sso.rd.go.th/ws_rdsso/Service")]
    public partial class JobCls
    {
        
        private string job_IDField;
        
        private string job_NameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Job_ID
        {
            get
            {
                return this.job_IDField;
            }
            set
            {
                this.job_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Job_Name
        {
            get
            {
                return this.job_NameField;
            }
            set
            {
                this.job_NameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws_sso.rd.go.th/ws_rdsso/Service")]
    public partial class LocCls
    {
        
        private string locIDField;
        
        private string locNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LocID
        {
            get
            {
                return this.locIDField;
            }
            set
            {
                this.locIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LocName
        {
            get
            {
                return this.locNameField;
            }
            set
            {
                this.locNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws_sso.rd.go.th/ws_rdsso/Service")]
    public partial class ClientCls
    {
        
        private string clientMachineNumberField;
        
        private string clientIPField;
        
        private string clientMACField;
        
        private string clientLocationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ClientMachineNumber
        {
            get
            {
                return this.clientMachineNumberField;
            }
            set
            {
                this.clientMachineNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ClientIP
        {
            get
            {
                return this.clientIPField;
            }
            set
            {
                this.clientIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ClientMAC
        {
            get
            {
                return this.clientMACField;
            }
            set
            {
                this.clientMACField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ClientLocation
        {
            get
            {
                return this.clientLocationField;
            }
            set
            {
                this.clientLocationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws_sso.rd.go.th/ws_rdsso/Service")]
    public partial class UserStatusCls
    {
        
        private string userIDField;
        
        private string userStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserStatus
        {
            get
            {
                return this.userStatusField;
            }
            set
            {
                this.userStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws_sso.rd.go.th/ws_rdsso/Service")]
    public partial class TransCls
    {
        
        private string appIDField;
        
        private string appNameField;
        
        private string appTransIDField;
        
        private string appPrivilegesField;
        
        private string appPrivacyMethodsField;
        
        private string appUserGroupField;
        
        private string userIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AppID
        {
            get
            {
                return this.appIDField;
            }
            set
            {
                this.appIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AppName
        {
            get
            {
                return this.appNameField;
            }
            set
            {
                this.appNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AppTransID
        {
            get
            {
                return this.appTransIDField;
            }
            set
            {
                this.appTransIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AppPrivileges
        {
            get
            {
                return this.appPrivilegesField;
            }
            set
            {
                this.appPrivilegesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AppPrivacyMethods
        {
            get
            {
                return this.appPrivacyMethodsField;
            }
            set
            {
                this.appPrivacyMethodsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string AppUserGroup
        {
            get
            {
                return this.appUserGroupField;
            }
            set
            {
                this.appUserGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws_sso.rd.go.th/ws_rdsso/Service")]
    public partial class UserPKIMSCls
    {
        
        private string userIDField;
        
        private string userPINField;
        
        private string userRDCodeField;
        
        private string userPrefixField;
        
        private string userNameTHField;
        
        private string userSurNameTHField;
        
        private string userNameENField;
        
        private string userSurNameENField;
        
        private string userEMailField;
        
        private string userTypeField;
        
        private string userRankField;
        
        private string userPositionNoField;
        
        private string userLevelCField;
        
        private string userLevelNewField;
        
        private string userOfficeCodeField;
        
        private string userJobIDField;
        
        private string userWorkCodeField;
        
        private string userWorkJobIDField;
        
        private string userJobLevelField;
        
        private string userMainJobIDField;
        
        private string userMainJobNameField;
        
        private string userSubJobIDField;
        
        private string userSubJobNameField;
        
        private string userEsupTeamIDField;
        
        private string userEsupSubTeamIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserPIN
        {
            get
            {
                return this.userPINField;
            }
            set
            {
                this.userPINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UserRDCode
        {
            get
            {
                return this.userRDCodeField;
            }
            set
            {
                this.userRDCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UserPrefix
        {
            get
            {
                return this.userPrefixField;
            }
            set
            {
                this.userPrefixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string UserNameTH
        {
            get
            {
                return this.userNameTHField;
            }
            set
            {
                this.userNameTHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string UserSurNameTH
        {
            get
            {
                return this.userSurNameTHField;
            }
            set
            {
                this.userSurNameTHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string UserNameEN
        {
            get
            {
                return this.userNameENField;
            }
            set
            {
                this.userNameENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string UserSurNameEN
        {
            get
            {
                return this.userSurNameENField;
            }
            set
            {
                this.userSurNameENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string UserEMail
        {
            get
            {
                return this.userEMailField;
            }
            set
            {
                this.userEMailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string UserType
        {
            get
            {
                return this.userTypeField;
            }
            set
            {
                this.userTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string UserRank
        {
            get
            {
                return this.userRankField;
            }
            set
            {
                this.userRankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string UserPositionNo
        {
            get
            {
                return this.userPositionNoField;
            }
            set
            {
                this.userPositionNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string UserLevelC
        {
            get
            {
                return this.userLevelCField;
            }
            set
            {
                this.userLevelCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string UserLevelNew
        {
            get
            {
                return this.userLevelNewField;
            }
            set
            {
                this.userLevelNewField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string UserOfficeCode
        {
            get
            {
                return this.userOfficeCodeField;
            }
            set
            {
                this.userOfficeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string UserJobID
        {
            get
            {
                return this.userJobIDField;
            }
            set
            {
                this.userJobIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string UserWorkCode
        {
            get
            {
                return this.userWorkCodeField;
            }
            set
            {
                this.userWorkCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string UserWorkJobID
        {
            get
            {
                return this.userWorkJobIDField;
            }
            set
            {
                this.userWorkJobIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string UserJobLevel
        {
            get
            {
                return this.userJobLevelField;
            }
            set
            {
                this.userJobLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string UserMainJobID
        {
            get
            {
                return this.userMainJobIDField;
            }
            set
            {
                this.userMainJobIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string UserMainJobName
        {
            get
            {
                return this.userMainJobNameField;
            }
            set
            {
                this.userMainJobNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string UserSubJobID
        {
            get
            {
                return this.userSubJobIDField;
            }
            set
            {
                this.userSubJobIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string UserSubJobName
        {
            get
            {
                return this.userSubJobNameField;
            }
            set
            {
                this.userSubJobNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string UserEsupTeamID
        {
            get
            {
                return this.userEsupTeamIDField;
            }
            set
            {
                this.userEsupTeamIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string UserEsupSubTeamID
        {
            get
            {
                return this.userEsupSubTeamIDField;
            }
            set
            {
                this.userEsupSubTeamIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws_sso.rd.go.th/ws_rdsso/Service")]
    public partial class UserIdCls
    {
        
        private string userIDField;
        
        private string userPINField;
        
        private string userRDCodeField;
        
        private string userPrefixField;
        
        private string userNameTHField;
        
        private string userSurNameTHField;
        
        private string userNameENField;
        
        private string userSurNameENField;
        
        private string userEMailField;
        
        private string userTypeField;
        
        private string userRankField;
        
        private string userPositionNoField;
        
        private string userOfficeCodeField;
        
        private string userJobIDField;
        
        private string userWorkCodeField;
        
        private string userWorkJobIDField;
        
        private string userLevelCField;
        
        private string userLevelNewField;
        
        private string userLoginDateTimeField;
        
        private string clientIPField;
        
        private string clientMACField;
        
        private string tokenIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserPIN
        {
            get
            {
                return this.userPINField;
            }
            set
            {
                this.userPINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UserRDCode
        {
            get
            {
                return this.userRDCodeField;
            }
            set
            {
                this.userRDCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UserPrefix
        {
            get
            {
                return this.userPrefixField;
            }
            set
            {
                this.userPrefixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string UserNameTH
        {
            get
            {
                return this.userNameTHField;
            }
            set
            {
                this.userNameTHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string UserSurNameTH
        {
            get
            {
                return this.userSurNameTHField;
            }
            set
            {
                this.userSurNameTHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string UserNameEN
        {
            get
            {
                return this.userNameENField;
            }
            set
            {
                this.userNameENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string UserSurNameEN
        {
            get
            {
                return this.userSurNameENField;
            }
            set
            {
                this.userSurNameENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string UserEMail
        {
            get
            {
                return this.userEMailField;
            }
            set
            {
                this.userEMailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string UserType
        {
            get
            {
                return this.userTypeField;
            }
            set
            {
                this.userTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string UserRank
        {
            get
            {
                return this.userRankField;
            }
            set
            {
                this.userRankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string UserPositionNo
        {
            get
            {
                return this.userPositionNoField;
            }
            set
            {
                this.userPositionNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string UserOfficeCode
        {
            get
            {
                return this.userOfficeCodeField;
            }
            set
            {
                this.userOfficeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string UserJobID
        {
            get
            {
                return this.userJobIDField;
            }
            set
            {
                this.userJobIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string UserWorkCode
        {
            get
            {
                return this.userWorkCodeField;
            }
            set
            {
                this.userWorkCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string UserWorkJobID
        {
            get
            {
                return this.userWorkJobIDField;
            }
            set
            {
                this.userWorkJobIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string UserLevelC
        {
            get
            {
                return this.userLevelCField;
            }
            set
            {
                this.userLevelCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string UserLevelNew
        {
            get
            {
                return this.userLevelNewField;
            }
            set
            {
                this.userLevelNewField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string UserLoginDateTime
        {
            get
            {
                return this.userLoginDateTimeField;
            }
            set
            {
                this.userLoginDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string ClientIP
        {
            get
            {
                return this.clientIPField;
            }
            set
            {
                this.clientIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string ClientMAC
        {
            get
            {
                return this.clientMACField;
            }
            set
            {
                this.clientMACField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string TokenID
        {
            get
            {
                return this.tokenIDField;
            }
            set
            {
                this.tokenIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws_sso.rd.go.th/ws_rdsso/Service")]
    public partial class User2Cls
    {
        
        private string userIDField;
        
        private string userPINField;
        
        private string userRDCodeField;
        
        private string userPrefixField;
        
        private string userNameTHField;
        
        private string userSurNameTHField;
        
        private string userNameENField;
        
        private string userSurNameENField;
        
        private string userEMailField;
        
        private string userTypeField;
        
        private string userRankField;
        
        private string userPositionNoField;
        
        private string userOfficeCodeField;
        
        private string userJobIDField;
        
        private string userWorkCodeField;
        
        private string userWorkJobIDField;
        
        private string userLevelCField;
        
        private string userLevelNewField;
        
        private string userLoginDateTimeField;
        
        private string clientIPField;
        
        private string clientMACField;
        
        private string tokenIDField;
        
        private string userJobLevelField;
        
        private string userMainJobIDField;
        
        private string userMainJobNameField;
        
        private string userSubJobIDField;
        
        private string userSubJobNameField;
        
        private string userEsupTeamIDField;
        
        private string userEsupSubTeamIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserPIN
        {
            get
            {
                return this.userPINField;
            }
            set
            {
                this.userPINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UserRDCode
        {
            get
            {
                return this.userRDCodeField;
            }
            set
            {
                this.userRDCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UserPrefix
        {
            get
            {
                return this.userPrefixField;
            }
            set
            {
                this.userPrefixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string UserNameTH
        {
            get
            {
                return this.userNameTHField;
            }
            set
            {
                this.userNameTHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string UserSurNameTH
        {
            get
            {
                return this.userSurNameTHField;
            }
            set
            {
                this.userSurNameTHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string UserNameEN
        {
            get
            {
                return this.userNameENField;
            }
            set
            {
                this.userNameENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string UserSurNameEN
        {
            get
            {
                return this.userSurNameENField;
            }
            set
            {
                this.userSurNameENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string UserEMail
        {
            get
            {
                return this.userEMailField;
            }
            set
            {
                this.userEMailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string UserType
        {
            get
            {
                return this.userTypeField;
            }
            set
            {
                this.userTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string UserRank
        {
            get
            {
                return this.userRankField;
            }
            set
            {
                this.userRankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string UserPositionNo
        {
            get
            {
                return this.userPositionNoField;
            }
            set
            {
                this.userPositionNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string UserOfficeCode
        {
            get
            {
                return this.userOfficeCodeField;
            }
            set
            {
                this.userOfficeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string UserJobID
        {
            get
            {
                return this.userJobIDField;
            }
            set
            {
                this.userJobIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string UserWorkCode
        {
            get
            {
                return this.userWorkCodeField;
            }
            set
            {
                this.userWorkCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string UserWorkJobID
        {
            get
            {
                return this.userWorkJobIDField;
            }
            set
            {
                this.userWorkJobIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string UserLevelC
        {
            get
            {
                return this.userLevelCField;
            }
            set
            {
                this.userLevelCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string UserLevelNew
        {
            get
            {
                return this.userLevelNewField;
            }
            set
            {
                this.userLevelNewField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string UserLoginDateTime
        {
            get
            {
                return this.userLoginDateTimeField;
            }
            set
            {
                this.userLoginDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string ClientIP
        {
            get
            {
                return this.clientIPField;
            }
            set
            {
                this.clientIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string ClientMAC
        {
            get
            {
                return this.clientMACField;
            }
            set
            {
                this.clientMACField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string TokenID
        {
            get
            {
                return this.tokenIDField;
            }
            set
            {
                this.tokenIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string UserJobLevel
        {
            get
            {
                return this.userJobLevelField;
            }
            set
            {
                this.userJobLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string UserMainJobID
        {
            get
            {
                return this.userMainJobIDField;
            }
            set
            {
                this.userMainJobIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string UserMainJobName
        {
            get
            {
                return this.userMainJobNameField;
            }
            set
            {
                this.userMainJobNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string UserSubJobID
        {
            get
            {
                return this.userSubJobIDField;
            }
            set
            {
                this.userSubJobIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string UserSubJobName
        {
            get
            {
                return this.userSubJobNameField;
            }
            set
            {
                this.userSubJobNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string UserEsupTeamID
        {
            get
            {
                return this.userEsupTeamIDField;
            }
            set
            {
                this.userEsupTeamIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string UserEsupSubTeamID
        {
            get
            {
                return this.userEsupSubTeamIDField;
            }
            set
            {
                this.userEsupSubTeamIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface ServiceSoapChannel : SSOProductionService.ServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<SSOProductionService.ServiceSoap>, SSOProductionService.ServiceSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SSOProductionService.UserCls> Get_SSO_UserAsync(string UserID, string AppId, string Pwd_Authen)
        {
            return base.Channel.Get_SSO_UserAsync(UserID, AppId, Pwd_Authen);
        }
        
        public System.Threading.Tasks.Task<SSOProductionService.User2Cls> Get_SSO_User2Async(string UserID, string AppId, string Pwd_Authen)
        {
            return base.Channel.Get_SSO_User2Async(UserID, AppId, Pwd_Authen);
        }
        
        public System.Threading.Tasks.Task<SSOProductionService.UserIdCls> Get_SSO_UserByIDAsync(string UserID, string AppId, string Pwd_Authen)
        {
            return base.Channel.Get_SSO_UserByIDAsync(UserID, AppId, Pwd_Authen);
        }
        
        public System.Threading.Tasks.Task<SSOProductionService.UserPKIMSCls> Get_SSO_UserPKIMSAsync(string UserID, string UserPKIMS_ID, string UserPKIMS_PWD)
        {
            return base.Channel.Get_SSO_UserPKIMSAsync(UserID, UserPKIMS_ID, UserPKIMS_PWD);
        }
        
        public System.Threading.Tasks.Task<SSOProductionService.TransCls> Get_SSO_TransactionAsync(string UserID, string AppId, string Pwd_Authen)
        {
            return base.Channel.Get_SSO_TransactionAsync(UserID, AppId, Pwd_Authen);
        }
        
        public System.Threading.Tasks.Task<SSOProductionService.UserStatusCls> Get_SSO_StatusUserAsync(string UserID, string AppId, string Pwd_Authen)
        {
            return base.Channel.Get_SSO_StatusUserAsync(UserID, AppId, Pwd_Authen);
        }
        
        public System.Threading.Tasks.Task<SSOProductionService.ClientCls> Get_SSO_ClientAsync(string ClientIP, string AppId, string Pwd_Authen)
        {
            return base.Channel.Get_SSO_ClientAsync(ClientIP, AppId, Pwd_Authen);
        }
        
        public System.Threading.Tasks.Task<SSOProductionService.LocCls> Get_Location_NameAsync(string AppId, string Pwd_Authen, string Loc_ID)
        {
            return base.Channel.Get_Location_NameAsync(AppId, Pwd_Authen, Loc_ID);
        }
        
        public System.Threading.Tasks.Task<string[]> Get_JobAsync(string AppId, string Pwd_Authen, string Loc_ID)
        {
            return base.Channel.Get_JobAsync(AppId, Pwd_Authen, Loc_ID);
        }
        
        public System.Threading.Tasks.Task<SSOProductionService.JobCls> Get_Job_NameAsync(string AppId, string Pwd_Authen, string Job_ID)
        {
            return base.Channel.Get_Job_NameAsync(AppId, Pwd_Authen, Job_ID);
        }
        
        public System.Threading.Tasks.Task<string> TestAABAsync(int A)
        {
            return base.Channel.TestAABAsync(A);
        }
        
        public System.Threading.Tasks.Task<string[]> Get_User_UnderLocAsync(string AppId, string Pwd_Authen, string Loc_ID)
        {
            return base.Channel.Get_User_UnderLocAsync(AppId, Pwd_Authen, Loc_ID);
        }
        
        public System.Threading.Tasks.Task<string[]> Get_User_UnderJobAsync(string AppId, string Pwd_Authen, string Loc_ID, string Job_ID)
        {
            return base.Channel.Get_User_UnderJobAsync(AppId, Pwd_Authen, Loc_ID, Job_ID);
        }
        
        public System.Threading.Tasks.Task<SSOProductionService.UserLogCls> SSO_APP_Transaction_LogAsync(string UserID, string AppId, string TokenID, string AppTransID, string Pwd_Authen)
        {
            return base.Channel.SSO_APP_Transaction_LogAsync(UserID, AppId, TokenID, AppTransID, Pwd_Authen);
        }
        
        public System.Threading.Tasks.Task<SSOProductionService.UserLogCls> SSO_App_LogOutAsync(string UserID, string AppId, string TokenID, string Pwd_Authen)
        {
            return base.Channel.SSO_App_LogOutAsync(UserID, AppId, TokenID, Pwd_Authen);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://ws_sso.rd.go.th/ws_rdsso/Service.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://ws_sso.rd.go.th/ws_rdsso/Service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ServiceSoap,
            
            ServiceSoap12,
        }
    }
}
