//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSEOffice
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wservice.rd.go.th/ServiceEoffice/AuthenUserEoffice1/", ConfigurationName="WSEOffice.AuthenUserEoffice1Soap")]
    public interface AuthenUserEoffice1Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wservice.rd.go.th/ServiceEoffice/AuthenUserEoffice1/AuthenUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSEOffice.AuthenUserResponse> AuthenUserAsync(WSEOffice.AuthenUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wservice.rd.go.th/ServiceEoffice/AuthenUserEoffice1/HeadGrpofExpert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSEOffice.DataUser[]> HeadGrpofExpertAsync(string CheckUser, string CheckPass, string FName, string LName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wservice.rd.go.th/ServiceEoffice/AuthenUserEoffice1/AuthenbyName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSEOffice.DataUser[]> AuthenbyNameAsync(string CheckUser, string CheckPass, string FName, string LName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wservice.rd.go.th/ServiceEoffice/AuthenUserEoffice1/AuthenbyGrpName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSEOffice.DataUser[]> AuthenbyGrpNameAsync(string CheckUser, string CheckPass, string GrpName);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wservice.rd.go.th/ServiceEoffice/AuthenUserEoffice1/")]
    public partial class DataUser
    {
        
        private bool authenField;
        
        private string idField;
        
        private string tITLEField;
        
        private string fNAMEField;
        
        private string lNAMEField;
        
        private string uIDField;
        
        private string pASSWORDField;
        
        private string eMAILField;
        
        private string pOSNAMEField;
        
        private string eMPSTATUSField;
        
        private string bIRTHField;
        
        private string cLASS_dataField;
        
        private string sKILLIDField;
        
        private string eMPTYPEField;
        
        private string oFFICEIDField;
        
        private string oFFICENAMEField;
        
        private string pINField;
        
        private string pOSITION_MField;
        
        private string cLASS_NEWField;
        
        private string lEVELField;
        
        private string pOSACTField;
        
        private string gROUPNAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Authen
        {
            get
            {
                return this.authenField;
            }
            set
            {
                this.authenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TITLE
        {
            get
            {
                return this.tITLEField;
            }
            set
            {
                this.tITLEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FNAME
        {
            get
            {
                return this.fNAMEField;
            }
            set
            {
                this.fNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LNAME
        {
            get
            {
                return this.lNAMEField;
            }
            set
            {
                this.lNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string UID
        {
            get
            {
                return this.uIDField;
            }
            set
            {
                this.uIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string PASSWORD
        {
            get
            {
                return this.pASSWORDField;
            }
            set
            {
                this.pASSWORDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string EMAIL
        {
            get
            {
                return this.eMAILField;
            }
            set
            {
                this.eMAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string POSNAME
        {
            get
            {
                return this.pOSNAMEField;
            }
            set
            {
                this.pOSNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string EMPSTATUS
        {
            get
            {
                return this.eMPSTATUSField;
            }
            set
            {
                this.eMPSTATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string BIRTH
        {
            get
            {
                return this.bIRTHField;
            }
            set
            {
                this.bIRTHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string CLASS_data
        {
            get
            {
                return this.cLASS_dataField;
            }
            set
            {
                this.cLASS_dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string SKILLID
        {
            get
            {
                return this.sKILLIDField;
            }
            set
            {
                this.sKILLIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string EMPTYPE
        {
            get
            {
                return this.eMPTYPEField;
            }
            set
            {
                this.eMPTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string OFFICEID
        {
            get
            {
                return this.oFFICEIDField;
            }
            set
            {
                this.oFFICEIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string OFFICENAME
        {
            get
            {
                return this.oFFICENAMEField;
            }
            set
            {
                this.oFFICENAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string PIN
        {
            get
            {
                return this.pINField;
            }
            set
            {
                this.pINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string POSITION_M
        {
            get
            {
                return this.pOSITION_MField;
            }
            set
            {
                this.pOSITION_MField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string CLASS_NEW
        {
            get
            {
                return this.cLASS_NEWField;
            }
            set
            {
                this.cLASS_NEWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string LEVEL
        {
            get
            {
                return this.lEVELField;
            }
            set
            {
                this.lEVELField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string POSACT
        {
            get
            {
                return this.pOSACTField;
            }
            set
            {
                this.pOSACTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string GROUPNAME
        {
            get
            {
                return this.gROUPNAMEField;
            }
            set
            {
                this.gROUPNAMEField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenUser", WrapperNamespace="http://wservice.rd.go.th/ServiceEoffice/AuthenUserEoffice1/", IsWrapped=true)]
    public partial class AuthenUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wservice.rd.go.th/ServiceEoffice/AuthenUserEoffice1/", Order=0)]
        public string CheckUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wservice.rd.go.th/ServiceEoffice/AuthenUserEoffice1/", Order=1)]
        public string CheckPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wservice.rd.go.th/ServiceEoffice/AuthenUserEoffice1/", Order=2)]
        public string UID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wservice.rd.go.th/ServiceEoffice/AuthenUserEoffice1/", Order=3)]
        public string Password;
        
        public AuthenUserRequest()
        {
        }
        
        public AuthenUserRequest(string CheckUser, string CheckPass, string UID, string Password)
        {
            this.CheckUser = CheckUser;
            this.CheckPass = CheckPass;
            this.UID = UID;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenUserResponse", WrapperNamespace="http://wservice.rd.go.th/ServiceEoffice/AuthenUserEoffice1/", IsWrapped=true)]
    public partial class AuthenUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wservice.rd.go.th/ServiceEoffice/AuthenUserEoffice1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WSEOffice.DataUser DataUser;
        
        public AuthenUserResponse()
        {
        }
        
        public AuthenUserResponse(WSEOffice.DataUser DataUser)
        {
            this.DataUser = DataUser;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface AuthenUserEoffice1SoapChannel : WSEOffice.AuthenUserEoffice1Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class AuthenUserEoffice1SoapClient : System.ServiceModel.ClientBase<WSEOffice.AuthenUserEoffice1Soap>, WSEOffice.AuthenUserEoffice1Soap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AuthenUserEoffice1SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(AuthenUserEoffice1SoapClient.GetBindingForEndpoint(endpointConfiguration), AuthenUserEoffice1SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenUserEoffice1SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AuthenUserEoffice1SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenUserEoffice1SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AuthenUserEoffice1SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenUserEoffice1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSEOffice.AuthenUserResponse> WSEOffice.AuthenUserEoffice1Soap.AuthenUserAsync(WSEOffice.AuthenUserRequest request)
        {
            return base.Channel.AuthenUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSEOffice.AuthenUserResponse> AuthenUserAsync(string CheckUser, string CheckPass, string UID, string Password)
        {
            WSEOffice.AuthenUserRequest inValue = new WSEOffice.AuthenUserRequest();
            inValue.CheckUser = CheckUser;
            inValue.CheckPass = CheckPass;
            inValue.UID = UID;
            inValue.Password = Password;
            return ((WSEOffice.AuthenUserEoffice1Soap)(this)).AuthenUserAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<WSEOffice.DataUser[]> HeadGrpofExpertAsync(string CheckUser, string CheckPass, string FName, string LName)
        {
            return base.Channel.HeadGrpofExpertAsync(CheckUser, CheckPass, FName, LName);
        }
        
        public System.Threading.Tasks.Task<WSEOffice.DataUser[]> AuthenbyNameAsync(string CheckUser, string CheckPass, string FName, string LName)
        {
            return base.Channel.AuthenbyNameAsync(CheckUser, CheckPass, FName, LName);
        }
        
        public System.Threading.Tasks.Task<WSEOffice.DataUser[]> AuthenbyGrpNameAsync(string CheckUser, string CheckPass, string GrpName)
        {
            return base.Channel.AuthenbyGrpNameAsync(CheckUser, CheckPass, GrpName);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AuthenUserEoffice1Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.AuthenUserEoffice1Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AuthenUserEoffice1Soap))
            {
                return new System.ServiceModel.EndpointAddress("http://wservice.rd.go.th/ServiceEoffice/AuthenUserEoffice1.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.AuthenUserEoffice1Soap12))
            {
                return new System.ServiceModel.EndpointAddress("http://wservice.rd.go.th/ServiceEoffice/AuthenUserEoffice1.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            AuthenUserEoffice1Soap,
            
            AuthenUserEoffice1Soap12,
        }
    }
}
